\ProvidesClass{templates/texcommon}

\LoadClass{article}

\RequirePackage[pdftex,active,tightpage]{preview}
\RequirePackage{amsmath}

\RequirePackage[sb]{libertine} % or \usepackage[sb]{libertinus}
\RequirePackage[T1]{fontenc}
\RequirePackage{textcomp}
\RequirePackage[varqu,varl]{zi4}% inconsolata for mono, not LibertineMono
\RequirePackage[amsthm]{libertinust1math} % slanted integrals, by default
\RequirePackage[scr=boondoxo,bb=boondox]{mathalpha} %Omit bb=boondox for default libertinus bb
